In [29]:
import numpy as np

class Node(object):
    def __init__(self, value):
        self.value = value
        self.edges = []

class Edge(object):
    def __init__(self, value, node_from, node_to):
        self.value = value
        self.node_from = node_from
        self.node_to = node_to

class Graph(object):
    def __init__(self, nodes=[], edges=[]):
        self.nodes = nodes
        self.edges = edges

    def insert_node(self, new_node_val):
        new_node = Node(new_node_val)
        self.nodes.append(new_node)
        
    def insert_edge(self, new_edge_val, node_from_val, node_to_val):
        from_found = None
        to_found = None
        for node in self.nodes:
            if node_from_val == node.value:
                from_found = node
            if node_to_val == node.value:
                to_found = node
        if from_found == None:
            from_found = Node(node_from_val)
            self.nodes.append(from_found)
        if to_found == None:
            to_found = Node(node_to_val)
            self.nodes.append(to_found)
        new_edge = Edge(new_edge_val, from_found, to_found)
        from_found.edges.append(new_edge)
        to_found.edges.append(new_edge)
        self.edges.append(new_edge)

    def get_edge_list(self):
        """Don't return a list of edge objects!
        Return a list of triples that looks like this:
        (Edge Value, From Node Value, To Node Value)"""
        edge_list = []
        for edge in self.edges:
            edge_list.append([edge.value, edge.node_from.value, edge.node_to.value])
        return edge_list

    def get_adjacency_list(self):
        """Don't return any Node or Edge objects!
        You'll return a list of lists.
        The indicies of the outer list represent
        "from" nodes.
        Each section in the list will store a list
        of tuples that looks like this:
        (To Node, Edge Value)"""
        # Traverse through self.edges, and split by the edge.node_from.value
        adjacency_dict = {}
        for edge in self.edges:
            if adjacency_dict.get(edge.node_from.value):
                adjacency_dict[edge.node_from.value].append([edge.node_to.value, edge.value])
            else:
                adjacency_dict[edge.node_from.value] = [[edge.node_to.value, edge.value]]
        
        adjacency_list = []
        for node_from_value in sorted(adjacency_dict.keys()):
            adjacency_list.append(adjacency_dict[node_from_value])
        
        return adjacency_list
    
    def get_adjacency_matrix(self):
        """Return a matrix, or 2D list.
        Row numbers represent from nodes,
        column numbers represent to nodes.
        Store the edge values in each spot,
        and a 0 if no edge exists."""
        num_nodes = len(self.nodes)
        
        # adj_mat = [[0]*num_nodes]*num_nodes
        adj_mat = np.zeros((num_nodes,num_nodes))
    
        for edge in self.edges:
            i = edge.node_from.value
            j = edge.node_to.value
            # adj_mat[i-1][j-1] = edge.value
            adj_mat[i-1,j-1] = edge.value
        
        return adj_mat

graph = Graph()
graph.insert_edge(100, 1, 2)
graph.insert_edge(101, 1, 3)
graph.insert_edge(102, 1, 4)
graph.insert_edge(103, 3, 4)
# Should be [(100, 1, 2), (101, 1, 3), (102, 1, 4), (103, 3, 4)]
print graph.get_edge_list()
# Should be [None, [(2, 100), (3, 101), (4, 102)], None, [(4, 103)], None]
print graph.get_adjacency_list()
# Should be [[0, 0, 0, 0, 0], [0, 0, 100, 101, 102], [0, 0, 0, 0, 0], [0, 0, 0, 0, 103], [0, 0, 0, 0, 0]]
print graph.get_adjacency_matrix()

[[100, 1, 2], [101, 1, 3], [102, 1, 4], [103, 3, 4]]
[[[2, 100], [3, 101], [4, 102]], [[4, 103]]]
[[ 0.  1.  1.  1.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  1.]
 [ 1.  0.  1.  0.]]


In [31]:
a = {}
a[1] = 2
a['b'] = 4
print(a.items())
b = []
b.append(a.items())
print(b)

print(a.get(2))

[(1, 2), ('b', 4)]
[[(1, 2), ('b', 4)]]
None
